#include "commonFunctions.h"
#define NUMBER_OF_TRANSACTIONS_PER_TICK 1024
#define NUMBER_OF_SPECIAL_EVENT_PER_TICK 6
#define SIGNATURE_SIZE 64
#define SPECTRUM_DEPTH 24 // Is derived from SPECTRUM_CAPACITY (=N)
#define ASSETS_DEPTH 24 // Is derived from ASSETS_CAPACITY (=N)
#define NUMBER_OF_COMPUTORS 676
#define REQUEST_TICK_DATA 16
#define BROADCAST_TRANSACTION 24
#define REQUEST_CURRENT_TICK_INFO 27
#define RESPOND_CURRENT_TICK_INFO 28
#define REQUEST_TICK_TRANSACTIONS 29
#define REQUEST_COMPUTOR_LIST 11
#define RESPOND_COMPUTOR_LIST 2
#define BROADCAST_TICK_VOTE 3

#define SC_INITIALIZE_TX (NUMBER_OF_TRANSACTIONS_PER_TICK + 0)
#define SC_BEGIN_EPOCH_TX (NUMBER_OF_TRANSACTIONS_PER_TICK + 1)
#define SC_BEGIN_TICK_TX (NUMBER_OF_TRANSACTIONS_PER_TICK + 2)
#define SC_END_TICK_TX (NUMBER_OF_TRANSACTIONS_PER_TICK + 3)
#define SC_END_EPOCH_TX (NUMBER_OF_TRANSACTIONS_PER_TICK + 4)
#define SC_NOTIFICATION_TX (NUMBER_OF_TRANSACTIONS_PER_TICK + 5)